"""Comprehensive Banking Knowledge Base - 200+ documents covering all banking domains."""

BANKING_KNOWLEDGE_BASE = [
    # ==================== ACCOUNT OPERATIONS ====================
    {"id": "ACC-001", "title": "Savings Account Opening Procedure", "category": "operations", "access_level": "general",
     "content": "Savings Account Opening Procedure (SOP-ACC-001): Step 1: Customer visits the branch or applies online. Step 2: Collect KYC documents - Aadhaar Card, PAN Card, Passport-size photographs (2), Address Proof (Utility bill/Passport/Voter ID). Step 3: Fill Account Opening Form (AOF) with personal details, nominee information, and initial deposit details. Step 4: Verify documents against original copies. Step 5: Perform Video KYC for online applications or in-person verification at branch. Step 6: Minimum initial deposit of INR 500 for regular savings, INR 10,000 for premium savings. Step 7: Issue Welcome Kit containing debit card, cheque book, passbook, and internet banking credentials. Step 8: Activate account within 24 hours of document verification. TAT: 2-3 working days for complete account activation."},
    
    {"id": "ACC-002", "title": "Current Account Opening for Businesses", "category": "operations", "access_level": "general",
     "content": "Current Account Opening for Business Entities (SOP-ACC-002): Required Documents: Certificate of Incorporation/Registration, Memorandum of Association, Articles of Association, Board Resolution for account opening, PAN of the company, GST Registration Certificate, List of Directors/Partners with KYC, Proof of registered office address. Minimum Balance: INR 10,000 for sole proprietorship, INR 25,000 for partnership firms, INR 50,000 for private limited companies. Features: Unlimited transactions, overdraft facility available, multi-signatory options, bulk payment processing. TAT: 5-7 working days."},
    
    {"id": "ACC-003", "title": "KYC Policy and Procedures", "category": "compliance", "access_level": "general",
     "content": "Know Your Customer (KYC) Policy (POL-KYC-001): As per RBI Master Direction on KYC dated February 2016 (updated 2024): Customer Due Diligence (CDD) must be performed at: (a) Account opening, (b) When there is doubt about data veracity, (c) When transaction pattern changes significantly. Acceptable KYC Documents: Identity Proof - Aadhaar, PAN, Passport, Voter ID, Driving License. Address Proof - Aadhaar, Utility Bills (not older than 2 months), Bank Statement, Rental Agreement. Enhanced Due Diligence (EDD) required for: Politically Exposed Persons (PEPs), High-risk customers, Non-face-to-face customers, Customers from high-risk jurisdictions. KYC must be updated every 2 years for high-risk, 8 years for medium-risk, and 10 years for low-risk customers. V-CIP (Video-based Customer Identification Process) is permitted as per RBI circular dated January 2020."},
    
    {"id": "ACC-004", "title": "Account Closure Procedure", "category": "operations", "access_level": "general",
     "content": "Account Closure Procedure (SOP-ACC-004): Step 1: Customer submits Account Closure Request Form at the branch. Step 2: Verify identity of the account holder. Step 3: Check for any outstanding loans, liens, or SI/ECS mandates linked to the account. Step 4: Cancel all standing instructions, direct debits, and linked services. Step 5: Return unused cheque leaves. Step 6: Calculate closing balance including any accrued interest and applicable charges. Step 7: Account closure charges: NIL if account age > 1 year, INR 500 if < 1 year for savings account. Step 8: Issue final payment via demand draft or transfer to another account. Step 9: Deactivate linked debit card and internet banking. Step 10: Retain records for minimum 5 years as per RBI guidelines. TAT: 3-5 working days."},
    
    {"id": "ACC-005", "title": "Dormant and Inactive Account Policy", "category": "operations", "access_level": "general",
     "content": "Dormant and Inactive Account Management (POL-ACC-005): Definitions: Inactive Account - No customer-initiated transactions for 12 months. Dormant Account - No customer-initiated transactions for 24 months. Procedures: After 12 months of inactivity, send notification to customer via SMS/Email/Letter. After 24 months, classify as dormant and restrict debit transactions. Reactivation requires customer to visit branch with KYC documents. For unclaimed deposits (10+ years), transfer to RBI's Depositor Education and Awareness Fund (DEAF) as per Section 26A of Banking Regulation Act. Interest continues to accrue on dormant accounts."},
    
    {"id": "ACC-006", "title": "Joint Account Operations", "category": "operations", "access_level": "general",
     "content": "Joint Account Operations (SOP-ACC-006): Modes of Operation: (a) Either or Survivor (E/S) - Any one holder can operate, (b) Former or Survivor (F/S) - First holder operates during lifetime, (c) Anyone or Survivor - Any holder can operate independently, (d) Jointly - All holders must sign. In case of death of one joint holder: E/S mode - Surviving holder continues to operate. Jointly mode - Account is frozen until legal heir succession. Nomination is separate from joint holding - nominee gets custody, not ownership. All joint holders must complete KYC independently."},

    {"id": "ACC-007", "title": "Minor Account Operations", "category": "operations", "access_level": "general",
     "content": "Minor Account Operations (SOP-ACC-007): Accounts for minors below 10 years must be operated by natural/legal guardian. Minors above 10 years can operate account independently with guardian consent. On attaining majority (18 years): Account must be converted to regular account. Fresh KYC of the major is required. Guardian's role is terminated. New specimen signature must be registered. Minor accounts cannot have overdraft/credit facilities. Savings account only - no current accounts for minors."},

    # ==================== LOAN PRODUCTS ====================
    {"id": "LOAN-001", "title": "Home Loan Policy and Procedures", "category": "operations", "access_level": "general",
     "content": "Home Loan Policy (POL-LOAN-001): Eligibility: Salaried employees aged 21-60, Self-employed aged 25-65. Minimum income: INR 25,000/month (salaried), INR 3,00,000/year (self-employed). Loan Amount: Up to 80% of property value for loans up to INR 30 lakhs, 75% for loans above INR 30 lakhs up to INR 75 lakhs, 70% for loans above INR 75 lakhs (as per RBI LTV norms). Tenure: Maximum 30 years, not exceeding retirement age. Interest Rate: Linked to RLLR (Repo Linked Lending Rate). Processing Fee: 0.50% of loan amount + GST. Required Documents: Income proof (salary slips, ITR), Property documents, KYC, Bank statements (6 months), Employment proof. Disbursement: Stage-wise for under-construction, lump-sum for ready properties. Pre-payment: No prepayment charges for floating rate loans (as per RBI circular)."},
    
    {"id": "LOAN-002", "title": "Personal Loan Guidelines", "category": "operations", "access_level": "general",
     "content": "Personal Loan Guidelines (POL-LOAN-002): Eligibility: Salaried with minimum 2 years experience, minimum salary INR 20,000/month. Loan Amount: 10x to 24x monthly salary, maximum INR 40 lakhs. Tenure: 12 to 60 months. Interest Rate: 10.49% to 19.99% p.a. based on credit score and profile. CIBIL Score requirement: Minimum 700 for approval, 750+ for best rates. Processing Fee: 1-2% of loan amount. Documentation: KYC, Salary slips (3 months), Bank statements (6 months), Employment letter. EMI calculation: EMI = P × r × (1+r)^n / ((1+r)^n - 1) where P = Principal, r = monthly interest rate, n = number of EMIs. Foreclosure: Allowed after 12 EMIs, charges of 2-4% on outstanding principal for fixed rate loans. No foreclosure charges for floating rate loans."},
    
    {"id": "LOAN-003", "title": "Business Loan and MSME Lending", "category": "operations", "access_level": "general",
     "content": "Business Loan and MSME Lending Policy (POL-LOAN-003): MSME Classification (as per revised definition 2020): Micro - Investment up to INR 1 crore, Turnover up to INR 5 crore. Small - Investment up to INR 10 crore, Turnover up to INR 50 crore. Medium - Investment up to INR 50 crore, Turnover up to INR 250 crore. Products: MUDRA Loans (Shishu up to INR 50K, Kishore up to INR 5L, Tarun up to INR 10L), Working Capital loans, Term loans, CC/OD facilities. Collateral: Loans up to INR 10 lakhs are collateral-free under CGTMSE scheme. Priority Sector: MSME lending qualifies under Priority Sector Lending (PSL) - target 7.5% of ANBC."},
    
    {"id": "LOAN-004", "title": "Loan Recovery and NPA Management", "category": "compliance", "access_level": "compliance",
     "content": "Loan Recovery and NPA Management (POL-LOAN-004): NPA Classification as per RBI: Sub-standard - NPA for up to 12 months, Doubtful - NPA for more than 12 months, Loss - Loss identified by bank/auditor/RBI. Provisioning Requirements: Sub-standard: 15%, Doubtful (up to 1 year): 25%, Doubtful (1-3 years): 40%, Doubtful (3+ years): 100%, Loss: 100%. Recovery Process: Step 1: Send reminder after 30 days overdue. Step 2: Send legal notice after 60 days. Step 3: Classify as NPA after 90 days. Step 4: Initiate SARFAESI proceedings for secured loans > INR 2 lakhs. Step 5: File DRT application for loans > INR 20 lakhs. Step 6: Consider OTS (One Time Settlement) for compromise. Fair Practices Code must be followed - no coercive recovery methods."},
    
    {"id": "LOAN-005", "title": "Education Loan Scheme", "category": "operations", "access_level": "general",
     "content": "Education Loan Scheme (POL-LOAN-005): Eligibility: Indian national who has secured admission in recognized institution. Loan Amount: Up to INR 10 lakhs for domestic studies, Up to INR 20 lakhs for abroad studies. Collateral: Not required up to INR 7.5 lakhs. Margin: NIL for loans up to INR 4 lakhs, 5% for domestic above INR 4 lakhs, 15% for foreign studies. Repayment: Moratorium period - Course duration + 1 year. Maximum repayment: 15 years. Interest Rate: Linked to RLLR, subsidy available under Central Sector Interest Subsidy Scheme for economically weaker sections. Tax Benefit: Interest deduction under Section 80E of Income Tax Act for 8 years."},

    {"id": "LOAN-006", "title": "Gold Loan Procedures", "category": "operations", "access_level": "general",
     "content": "Gold Loan Procedures (SOP-LOAN-006): LTV Ratio: Maximum 75% of gold value (as per RBI circular). Purity Assessment: Minimum 18 carat gold accepted. Appraisal by certified appraiser in customer presence. Loan Tenure: 3 months to 12 months (renewable). Storage: Gold stored in tamper-proof packets in bank vault. Insurance coverage mandatory. Auction: If loan unpaid after 30 days of maturity notice, gold can be auctioned. 15 days prior notice required before auction. Surplus from auction returned to customer. Processing: Instant disbursal within 30 minutes of verification."},

    # ==================== COMPLIANCE & REGULATORY ====================
    {"id": "COMP-001", "title": "Anti-Money Laundering Policy", "category": "compliance", "access_level": "compliance",
     "content": "Anti-Money Laundering (AML) Policy (POL-AML-001): As per Prevention of Money Laundering Act (PMLA) 2002 and RBI Master Direction: Suspicious Transaction Reporting (STR): Banks must report to Financial Intelligence Unit (FIU-IND) within 7 days of identifying suspicion. Cash Transaction Report (CTR): All cash transactions above INR 10 lakhs (single or aggregate in a month) must be reported. Non-Profit Organization Transaction Report: Transactions above INR 10 lakhs. Red Flags: Unusual cash deposits, Rapid movement of funds, Structuring transactions to avoid thresholds, Transactions inconsistent with customer profile. Record Keeping: Maintain transaction records for minimum 5 years from date of transaction. CDD records to be maintained for 5 years after business relationship ends. Principal Officer must be appointed for AML compliance. Employee training on AML must be conducted annually."},
    
    {"id": "COMP-002", "title": "RBI Priority Sector Lending Guidelines", "category": "compliance", "access_level": "compliance",
     "content": "RBI Priority Sector Lending (PSL) Guidelines (REG-PSL-001): Total PSL Target: 40% of Adjusted Net Bank Credit (ANBC). Sub-targets: Agriculture - 18% of ANBC (of which 8% to Small and Marginal Farmers). Micro Enterprises - 7.5% of ANBC. Advances to Weaker Sections - 12% of ANBC. Categories under PSL: Agriculture, MSME, Education Loans, Housing Loans (up to INR 35 lakhs in metro, INR 25 lakhs in non-metro), Social Infrastructure, Renewable Energy, Export Credit, Others. Shortfall in PSL targets must be deposited in RIDF (Rural Infrastructure Development Fund) with NABARD or other funds specified by RBI."},
    
    {"id": "COMP-003", "title": "Basel III Capital Adequacy Framework", "category": "compliance", "access_level": "compliance",
     "content": "Basel III Capital Adequacy Framework (REG-BASEL-001): Minimum Capital Requirements for Indian Banks (as per RBI): Common Equity Tier 1 (CET1): 5.5% of Risk Weighted Assets. Additional Tier 1: 1.5%. Total Tier 1: 7%. Tier 2 Capital: 2%. Total Capital: 9%. Capital Conservation Buffer (CCB): 2.5% (fully phased in). Countercyclical Buffer: 0-2.5% (as decided by RBI). D-SIB Buffer: Additional 0.2-0.8% for Domestic Systemically Important Banks. Leverage Ratio: Minimum 4% for D-SIBs, 3.5% for others. Liquidity Coverage Ratio (LCR): Minimum 100% - sufficient HQLA to cover 30-day net cash outflow."},
    
    {"id": "COMP-004", "title": "FEMA Regulations for Foreign Exchange", "category": "compliance", "access_level": "compliance",
     "content": "FEMA Regulations for Foreign Exchange (REG-FEMA-001): Foreign Exchange Management Act (FEMA) 1999 regulates forex transactions. Current Account Transactions: Generally freely permissible. LRS (Liberalized Remittance Scheme): Up to USD 250,000 per financial year for resident individuals. Capital Account Transactions: Require RBI approval unless specifically permitted. ECB (External Commercial Borrowings): Governed by RBI framework with limits on cost, maturity, and end-use. FDI: Automatic route and Government route based on sector. Forex Dealers: Banks must be authorized as AD Category I/II/III. Full-Fledged Money Changers (FFMC) for retail forex. Reporting: All forex transactions must be reported to RBI through EDPMS/IDPMS portals."},

    {"id": "COMP-005", "title": "Data Protection and Privacy Policy", "category": "compliance", "access_level": "compliance",
     "content": "Data Protection and Privacy Policy (POL-DATA-001): Customer Data Classification: Public, Internal, Confidential, Restricted. Data Storage: Customer data must be stored in encrypted format (AES-256). Data in transit must use TLS 1.2 or higher. Data Retention: Transaction data - 10 years. KYC records - 5 years after relationship ends. Audit logs - 8 years. Access Control: Role-based access to customer data. Maker-Checker for data modifications. Data Masking: PAN, Aadhaar, Account numbers must be masked in displays and logs. Consent: Explicit customer consent required for data sharing with third parties. Right to erasure subject to regulatory retention requirements."},

    {"id": "COMP-006", "title": "Operational Risk Management Framework", "category": "risk", "access_level": "compliance",
     "content": "Operational Risk Management Framework (POL-ORM-001): Definition: Risk of loss from inadequate/failed internal processes, people, systems, or external events. Key Risk Indicators (KRIs): System downtime hours, Number of failed transactions, Customer complaints ratio, Employee attrition rate, Fraud incidents. Risk Assessment: Conduct RCSA (Risk and Control Self Assessment) quarterly. Maintain Loss Data Collection for all operational loss events above INR 1 lakh. Business Continuity: BCP and DR plans must be tested annually. RPO: 4 hours, RTO: 8 hours for critical systems. Three Lines of Defense: 1st - Business units, 2nd - Risk Management & Compliance, 3rd - Internal Audit."},

    {"id": "COMP-007", "title": "Fraud Risk Management", "category": "risk", "access_level": "compliance",
     "content": "Fraud Risk Management (POL-FRM-001): Fraud Classification: Cash shortage, Cheque fraud, Card fraud, Cyber fraud, Loan fraud, Identity theft. Reporting: All frauds above INR 1 lakh must be reported to RBI within 3 weeks. Frauds above INR 25 crore must have forensic audit. Early Warning Signals: Sudden spike in cash withdrawals, Multiple accounts with same address, Frequent change in authorized signatories, Round-tripping of funds. Whistle-blower: Protected Disclosure Scheme for reporting fraud. Staff Accountability: Fixing responsibility within 6 months for frauds above INR 25 lakhs."},

    # ==================== CARD OPERATIONS ====================
    {"id": "CARD-001", "title": "Credit Card Policy", "category": "operations", "access_level": "general",
     "content": "Credit Card Policy (POL-CARD-001): Eligibility: Minimum age 21 years, minimum income INR 15,000/month (salaried), good CIBIL score (700+). Card Limit: Based on income, credit score, and relationship value. Typically 2x-3x monthly income. Billing Cycle: Monthly statement with minimum due (5% of total outstanding or INR 200, whichever is higher). Interest: 2.5-3.5% per month (30-42% p.a.) on revolving credit from transaction date. Grace Period: Up to 50 days interest-free if full payment made by due date. Reward Points: 1 point per INR 100 spent, redeemable for cashback, travel, or merchandise. Annual Fee Waiver: Based on annual spend threshold. Lost Card: Report within 24 hours, zero liability if reported before fraudulent transaction."},
    
    {"id": "CARD-002", "title": "Debit Card Operations", "category": "operations", "access_level": "general",
     "content": "Debit Card Operations (SOP-CARD-002): Card Types: Classic, Gold, Platinum with different daily limits. Daily ATM Withdrawal Limit: Classic - INR 25,000, Gold - INR 50,000, Platinum - INR 1,00,000. Daily POS/Online Limit: Classic - INR 50,000, Gold - INR 2,00,000, Platinum - INR 5,00,000. International Usage: Must be separately enabled by customer. EMV Chip + PIN mandatory. Contactless (NFC): Enabled for transactions up to INR 5,000 without PIN. Card Replacement: Lost/damaged card replaced within 7 working days. Free first replacement, INR 200 for subsequent. ATM Transactions: First 5 transactions free at own bank ATM, first 3 free at other bank ATMs in metros (5 in non-metros). Beyond free limit: INR 21 per transaction."},
    
    {"id": "CARD-003", "title": "Card Dispute and Chargeback Process", "category": "operations", "access_level": "general",
     "content": "Card Dispute and Chargeback Process (SOP-CARD-003): Customer Dispute Filing: Customer must report unauthorized transaction within 3 working days for zero liability. Dispute Timeline: Within 3 days - Bank bears entire loss. 4-7 days - Customer liable up to INR 10,000/25,000 based on account type. Beyond 7 days - Customer liability as per bank policy. Process: Step 1: Customer files dispute via branch/call center/net banking. Step 2: Provisional credit within 10 days. Step 3: Investigation initiated with merchant/acquirer bank. Step 4: Chargeback filed via Visa/Mastercard/RuPay network. Step 5: Resolution within 90 days. Step 6: Final credit/debit based on outcome. RBI Circular: Banks must resolve unauthorized electronic transactions within 90 days and credit customer if found genuine."},

    # ==================== DIGITAL BANKING ====================
    {"id": "DIG-001", "title": "UPI Operations and Guidelines", "category": "operations", "access_level": "general",
     "content": "UPI (Unified Payments Interface) Operations (SOP-DIG-001): Transaction Limits: P2P - INR 1,00,000 per transaction. P2M - INR 1,00,000 for most categories, INR 2,00,000 for certain categories (Capital Markets, Insurance, Education). UPI Lite: Pre-loaded wallet for small value transactions up to INR 500 per transaction, wallet limit INR 4,000. UPI AutoPay: Recurring mandates up to INR 1,00,000 (increased from INR 15,000). Dispute Resolution: File within 30 days of transaction. UPI dispute must be resolved within 15-30 days by issuer PSP. Transaction Decline: Check beneficiary bank, VPA validity, daily limits, PSP server status. UPI charges: Free for P2P transactions. MDR applicable for P2M as per category."},
    
    {"id": "DIG-002", "title": "NEFT, RTGS, IMPS Comparison", "category": "operations", "access_level": "general",
     "content": "Fund Transfer Systems Comparison (REF-DIG-002): NEFT (National Electronic Fund Transfer): Available 24x7x365. No minimum/maximum limit. Settlement in half-hourly batches. Charges: Up to INR 10,000 - INR 2.50+GST, INR 10K-1L - INR 5+GST, INR 1L-2L - INR 15+GST, Above INR 2L - INR 25+GST. Free for savings account customers via internet/mobile banking. RTGS (Real Time Gross Settlement): Available 24x7x365. Minimum INR 2,00,000, no maximum. Real-time settlement. Charges: INR 2L-5L - INR 25+GST, Above INR 5L - INR 50+GST. Free via internet/mobile banking. IMPS (Immediate Payment Service): 24x7x365. Up to INR 5,00,000. Instant real-time transfer. Uses MMID+Mobile Number or Account+IFSC. Charges: INR 5-15 based on amount."},
    
    {"id": "DIG-003", "title": "Internet Banking Security Policy", "category": "operations", "access_level": "general",
     "content": "Internet Banking Security Policy (POL-DIG-003): Authentication: Two-factor authentication mandatory - Password + OTP/Token. Password Policy: Minimum 8 characters with uppercase, lowercase, number, and special character. Change every 90 days. Session Timeout: Auto logout after 5 minutes of inactivity. IP Whitelist: Available for corporate internet banking. Transaction Limits: Default daily limit, can be modified via branch/ATM. Beneficiary Cooling Period: 4-24 hours for new beneficiaries (configurable). Virtual Keyboard: Must be used for entering password. SSL/TLS: Minimum TLS 1.2 with certificate pinning. Device Binding: Mobile banking linked to specific device. Phishing Protection: Bank will never ask for OTP/password via email or phone."},

    {"id": "DIG-004", "title": "Mobile Banking Application Guidelines", "category": "operations", "access_level": "general",
     "content": "Mobile Banking Application Guidelines (SOP-DIG-004): Registration: Customer must have active internet banking or visit branch. Device binding through OTP verification. mPIN/Biometric authentication for transactions. Features: Balance inquiry, Mini statement, Fund transfer (NEFT/IMPS/UPI), Bill payments, Cheque book request, FD/RD creation, Card management, Loan EMI payment. Security: App integrity check on launch, Root/Jailbreak detection, SSL certificate pinning, Biometric authentication, Transaction PIN for financial transactions. Complaints: In-app complaint registration with tracking ID. Response within 48 hours for mobile banking issues."},

    # ==================== TREASURY AND FOREX ====================
    {"id": "TREAS-001", "title": "Trade Finance - Letter of Credit", "category": "operations", "access_level": "operations",
     "content": "Letter of Credit (LC) Operations (SOP-TREAS-001): Types: Sight LC (payment on presentation), Usance LC (deferred payment), Revolving LC, Transferable LC, Back-to-Back LC, Standby LC. Process Flow: Step 1: Buyer's bank (Issuing Bank) opens LC. Step 2: LC advised through Advising Bank to beneficiary. Step 3: Beneficiary ships goods and presents documents. Step 4: Documents examined for compliance with LC terms. Step 5: Payment released upon compliant presentation. Key Documents: Bill of Lading/Airway Bill, Commercial Invoice, Packing List, Certificate of Origin, Insurance Certificate. Commission: 0.10-0.50% per quarter on LC amount. Governed by UCP 600 (ICC Publication). Discrepancy handling: 5 banking days to examine documents."},

    {"id": "TREAS-002", "title": "Bank Guarantee Operations", "category": "operations", "access_level": "operations",
     "content": "Bank Guarantee (BG) Operations (SOP-TREAS-002): Types: Financial Guarantee (payment assurance), Performance Guarantee (contract performance), Bid Bond/EMD Guarantee, Advance Payment Guarantee, Deferred Payment Guarantee. Margin: 10-100% cash margin based on customer credit rating and relationship. Commission: 0.50-2.00% per annum on BG amount. Invocation: Beneficiary can invoke BG by submitting claim before expiry. Bank must honor unconditional guarantees within 3 banking days. Counter Guarantee: Required for overseas guarantees - issued through correspondent bank. Extension/Cancellation: Extension requires customer request and fresh approval. Cancellation only with beneficiary's written consent or on expiry."},

    # ==================== CUSTOMER SERVICE ====================
    {"id": "CS-001", "title": "Customer Complaint Handling SOP", "category": "customer_service", "access_level": "general",
     "content": "Customer Complaint Handling Standard Operating Procedure (SOP-CS-001): Channels: Branch, Call Center (toll-free), Email, Website, Social Media, Banking Ombudsman. Resolution TAT: Simple queries - same day. Account related - 3 working days. Card disputes - 7 working days (provisional credit in 10 days). Complex/cross-border - 30 days. Escalation Matrix: Level 1 - Branch Manager/Call Center Supervisor (within 3 days). Level 2 - Regional Manager/Nodal Officer (within 7 days). Level 3 - Principal Nodal Officer (within 15 days). Level 4 - Banking Ombudsman (if unresolved in 30 days). Complaint Tracking: Unique reference number provided. Status trackable via SMS/Website/App. Monthly complaint analysis report submitted to Board. Customer Compensation: INR 100/day for delayed resolution beyond TAT for valid complaints."},
    
    {"id": "CS-002", "title": "Banking Ombudsman Scheme", "category": "customer_service", "access_level": "general",
     "content": "RBI Integrated Ombudsman Scheme 2021 (REF-CS-002): Coverage: All complaints against banks, NBFCs, and payment system operators under one scheme. Eligibility: Customer must first complain to bank. If not resolved within 30 days, or if dissatisfied with resolution. Filing: Online via CMS portal (https://cms.rbi.org.in), Email, or physical complaint. Cost: Free of charge. No need for advocate/lawyer. Compensation: Up to INR 20 lakhs for financial loss. Up to INR 1 lakh for mental agony/harassment. Appellate Authority: If unsatisfied with Ombudsman decision, appeal within 30 days. Bank cannot appeal against customer-favoring decision."},

    # ==================== HR & ONBOARDING ====================
    {"id": "HR-001", "title": "New Employee Onboarding Guide", "category": "operations", "access_level": "general",
     "content": "New Employee Onboarding Guide (SOP-HR-001): Pre-joining: Offer letter, Background verification, Medical fitness certificate. Day 1: ID card issuance, System access creation, Compliance training overview, Department introduction. Week 1: Core banking system (CBS) training, AML/KYC awareness, Information security policy review, Clean desk policy briefing. Month 1: Product knowledge training, Customer service standards, Regulatory compliance overview, Shadow experienced staff. Month 2-3: Independent handling with supervision, Assessment and feedback. Mandatory Training: AML/KYC (annual), Information Security (annual), Sexual Harassment Prevention (annual), Compliance refresher (quarterly). Employee Code of Conduct: No acceptance of gifts above INR 1,000. Declaration of outside business interests. Mandatory leave of 10 consecutive days annually."},
    
    {"id": "HR-002", "title": "Employee Code of Conduct", "category": "operations", "access_level": "general",
     "content": "Employee Code of Conduct (POL-HR-002): Confidentiality: All customer and bank information is confidential. Breach of confidentiality is a disciplinary offense. Conflict of Interest: Employees must declare any conflict of interest. Cannot process transactions for family members without supervisor approval. Gift Policy: Gifts above INR 1,000 must be reported. No cash gifts accepted under any circumstances. Leave Policy: Employee must avail 10 consecutive days of mandatory leave annually (vigilance requirement). Trading: Employees in treasury/dealing desks must declare personal trading accounts. Insider trading strictly prohibited. Social Media: No discussion of bank's internal matters on social media. Personal views must carry disclaimer. Whistle-blower: Anonymous reporting channel available. Protection against retaliation guaranteed."},

    # ==================== INTEREST RATES & CHARGES ====================
    {"id": "RATE-001", "title": "Current Interest Rate Schedule", "category": "operations", "access_level": "general",
     "content": "Interest Rate Schedule (REF-RATE-001) - Effective Rates: SAVINGS ACCOUNT: Regular Savings - 2.70% p.a. (up to INR 50 lakhs), 3.00% p.a. (above INR 50 lakhs). FIXED DEPOSITS: 7 days to 45 days - 3.00%. 46 days to 179 days - 4.50%. 180 days to 364 days - 5.75%. 1 year to 2 years - 6.80%. 2 years to 3 years - 7.00%. 3 years to 5 years - 6.50%. 5 years to 10 years - 6.50%. Senior Citizens: Additional 0.50% on FD rates. LENDING RATES: RLLR (Repo Linked Lending Rate): 8.60% (Base). Home Loan: RLLR + 0.30% = 8.90% onwards. Personal Loan: RLLR + 2.00% = 10.60% onwards. Car Loan: RLLR + 1.00% = 9.60% onwards. Education Loan: RLLR + 0.75% = 9.35% onwards. MCLR (1 Year): 8.70%."},

    {"id": "RATE-002", "title": "Service Charges and Fees", "category": "operations", "access_level": "general",
     "content": "Schedule of Service Charges and Fees (REF-RATE-002): NON-MAINTENANCE CHARGES: Savings Account: INR 100/quarter if average monthly balance < INR 5,000 (metro), < INR 3,000 (non-metro). Current Account: INR 500/quarter if balance < INR 10,000. CHEQUE CHARGES: Cheque book (20 leaves) first free, subsequent INR 75+GST. Cheque return (issued) - INR 350+GST per instance. DD/PO: Up to INR 5,000 - INR 25, INR 5K-10K - INR 50, Above INR 10K - INR 3/thousand. CERTIFICATE CHARGES: Balance certificate - INR 100, Solvency certificate - INR 500, No-dues certificate - INR 200. LOCKER CHARGES: Small - INR 2,000/year, Medium - INR 4,000/year, Large - INR 8,000/year. GST applicable on all charges."},

    # ==================== DIGITAL LENDING & FINTECH ====================
    {"id": "FINTECH-001", "title": "Digital Lending Guidelines", "category": "compliance", "access_level": "compliance",
     "content": "RBI Digital Lending Guidelines (REG-DIG-001): Key Provisions (effective September 2022): All loan disbursements must be directly to borrower's bank account. Repayments must be from borrower's bank account to regulated entity. No pass-through of funds via third-party (LSP/DLA). Key Fact Statement (KFS): Must be provided before loan execution containing: APR, recovery mechanism, cooling-off period details, penal charges. Cooling Off Period: Borrower can exit digital loan within stipulated period (minimum 3 days). LSP (Lending Service Provider): Must be registered with RBI. Cannot access customer's mobile data. First Loss Default Guarantee (FLDG): Capped at 5% of loan portfolio. Data Privacy: No biometric or personal data storage by LSPs without explicit consent."},

    {"id": "FINTECH-002", "title": "Account Aggregator Framework", "category": "operations", "access_level": "operations",
     "content": "Account Aggregator (AA) Framework (REG-AA-001): Definition: NBFC-AA is a consent-based data sharing framework regulated by RBI. Key Entities: FIP (Financial Information Provider) - Banks, Insurance, MFs. FIU (Financial Information User) - Lenders, Insurance companies. AA - Intermediary facilitating consent and data flow. Process: Customer gives consent via AA app/portal. AA fetches data from FIP and shares with FIU. Consent is granular - purpose, duration, frequency specified. Data Types: Bank statements, FD/RD details, Insurance policies, MF holdings, Pension data, Tax filings. Benefits for Banking: Faster loan processing, Reduced document collection, Real-time financial profile assessment, Reduced fraud through verified data."},

    # ==================== PAYMENTS & SETTLEMENTS ====================
    {"id": "PAY-001", "title": "Cheque Truncation System", "category": "operations", "access_level": "general",
     "content": "Cheque Truncation System (CTS) Operations (SOP-PAY-001): CTS eliminates physical movement of cheques between banks. Process: Presenting bank captures cheque image and MICR data. Electronic image sent to drawee bank for clearing. Settlement through RBI's clearing system. Timelines: T+0 for local clearing, T+1 for grid-based clearing. Positive Pay System: Mandatory for cheques above INR 50,000. Drawer must provide cheque details (number, date, payee, amount) in advance. If details don't match, cheque returned. CTS-2010 Standard: All cheques must conform to CTS-2010 standard with security features. Return Reasons: Insufficient funds, Payment stopped, Signature mismatch, Account closed, Cheque post-dated, Amount in words and figures differ."},

    {"id": "PAY-002", "title": "NACH and ECS Mandate Management", "category": "operations", "access_level": "general",
     "content": "NACH and ECS Mandate Management (SOP-PAY-002): NACH (National Automated Clearing House): Replaced ECS for bulk transactions. Types: NACH Credit (salary, dividend payments), NACH Debit (EMI, SIP, insurance premium). e-Mandate: Electronic mandate registration via net banking/debit card/Aadhaar. Maximum amount and frequency specified in mandate. Amendment/Cancellation: Customer can modify or cancel mandate through bank. 30-day notice period for cancellation. Dispute: If unauthorized debit, customer files dispute within 30 days. Amount reversed within 10 working days. Corporate Registration: Companies must register as sponsor bank users. Batch submission by cut-off time for same-day processing."},

    # ==================== RISK MANAGEMENT ====================
    {"id": "RISK-001", "title": "Credit Risk Assessment Framework", "category": "risk", "access_level": "compliance",
     "content": "Credit Risk Assessment Framework (POL-RISK-001): Credit Appraisal Process: Step 1: Application screening and preliminary assessment. Step 2: Credit score check (CIBIL/Experian/CRIF/Equifax). Step 3: Financial statement analysis (3 years for business loans). Step 4: Cash flow analysis and DSCR calculation. Step 5: Collateral valuation. Step 6: Industry/Sector risk assessment. Step 7: Credit committee approval based on delegation of powers. Key Ratios: Debt-to-Equity: Should not exceed 3:1 for manufacturing, 4:1 for trading. Current Ratio: Minimum 1.33. DSCR (Debt Service Coverage Ratio): Minimum 1.50. Interest Coverage Ratio: Minimum 2.0. Credit Rating: Internal rating models calibrated against external ratings. Rating migration analysis performed quarterly. Portfolio Concentration: Single borrower limit - 15% of capital funds. Group borrower limit - 25% of capital funds."},

    {"id": "RISK-002", "title": "Market Risk Management", "category": "risk", "access_level": "compliance",
     "content": "Market Risk Management Framework (POL-RISK-002): Market Risk: Risk of loss from adverse movement in market prices (interest rates, forex, equity). Interest Rate Risk in Banking Book (IRRBB): Duration Gap Analysis performed monthly. NII (Net Interest Income) sensitivity to rate changes. EVE (Economic Value of Equity) impact assessment. stress testing for +/- 200 bps parallel shift. Forex Risk: Open position limits - Daylight and Overnight. AGL (Aggregate Gap Limit) monitored daily. VaR (Value at Risk): Calculated daily using Historical Simulation method. 99% confidence interval, 1-day and 10-day holding period. Backtesting: Daily backtesting of VaR models. If exceptions exceed 4 in 250 days, model recalibration required. Stress Testing: Quarterly stress tests covering extreme but plausible scenarios."},

    # ==================== SAFE DEPOSIT LOCKER ====================
    {"id": "LOCK-001", "title": "Safe Deposit Locker Operations", "category": "operations", "access_level": "general",
     "content": "Safe Deposit Locker Operations (SOP-LOCK-001): As per revised RBI guidelines (January 2022): Allotment: Based on availability, maintain computerized wait list. Agreement: Standardized locker agreement as per IBA model. No blanket lien on locker contents for loan dues. Rent: Annual rent based on locker size. Non-payment of rent for 3 years - break open procedure. Access: During bank working hours. Joint holders based on operating instructions. Nomination facility available. Bank Liability: Bank liable for loss due to its negligence, fraud by employees, fire/theft/building collapse/dacoit. Compensation: Up to 100x annual rent for proven bank negligence. Insurance: Bank must arrange insurance for locker area. Breaking Open: After due notice (last known address + newspaper), locker may be broken open. Contents inventoried with independent witnesses and kept in sealed cover."},

    # ==================== INVESTMENT PRODUCTS ====================
    {"id": "INV-001", "title": "Fixed Deposit and Recurring Deposit", "category": "operations", "access_level": "general",
     "content": "Fixed Deposit (FD) and Recurring Deposit (RD) Guidelines (SOP-INV-001): FIXED DEPOSIT: Minimum Amount: INR 1,000. Tenure: 7 days to 10 years. Premature Withdrawal: Allowed with 0.50-1.00% penalty on applicable rate. Rate applicable is for the period deposit has actually remained. Auto-Renewal: Option available at time of deposit creation. Tax Deductible at Source: TDS @10% if interest exceeds INR 40,000/year (INR 50,000 for seniors). No TDS if Form 15G/15H submitted. Loan against FD: Up to 90% of FD value at FD rate + 1-2%. Tax Saver FD: 5-year lock-in, eligible for Section 80C deduction up to INR 1.5 lakhs. RECURRING DEPOSIT: Minimum: INR 100/month. Tenure: 6 months to 10 years. Penalty for late installment: INR 1.50 per INR 100 per month of default."},

    {"id": "INV-002", "title": "Government Schemes - PMJDY, PMSBY, APY", "category": "operations", "access_level": "general",
     "content": "Government Banking Schemes (REF-INV-002): PMJDY (Pradhan Mantri Jan Dhan Yojana): Zero balance account with RuPay debit card. Accidental insurance of INR 2 lakhs. Overdraft up to INR 10,000 for eligible accounts. PMSBY (Pradhan Mantri Suraksha Bima Yojana): Accidental death/disability insurance at INR 20/year. Coverage: INR 2 lakhs for death and permanent disability, INR 1 lakh for partial disability. Age: 18-70 years. PMJJBY (Pradhan Mantri Jeevan Jyoti Bima Yojana): Life insurance at INR 436/year. Coverage: INR 2 lakhs. Age: 18-55 years. APY (Atal Pension Yojana): Guaranteed pension of INR 1,000-5,000/month after age 60. Contribution based on entry age and pension amount. Government co-contributes 50% for 5 years for unorganized sector workers."},

    # ==================== ADDITIONAL IMPORTANT TOPICS ====================
    {"id": "GEN-001", "title": "Nomination Facility in Banking", "category": "operations", "access_level": "general",
     "content": "Nomination Facility in Banking (SOP-GEN-001): As per Banking Regulation Act Section 45ZA-ZF: Purpose: Facilitates hassle-free settlement of claims on death of account holder. Registration: At time of account opening or subsequently. Form DA-1 for deposits, Form SL for safe deposit lockers. Modification: Can be modified/cancelled anytime during account holder's lifetime. Multiple Nominees: Allowed in joint accounts - nomination in favor of all joint holders or specific person. Minor Nominee: Guardian details required if nominee is minor. Claim Settlement: Nominee receives deposit as trustee. Bank not required to check will/succession certificate if valid nomination exists. TAT: Claim settlement within 15 days of submitting required documents. Nominee vs Legal Heir: Nominee is custodian, not owner. In case of dispute, legal heirs can challenge through court."},

    {"id": "GEN-002", "title": "Priority Sector Lending Certificates", "category": "compliance", "access_level": "compliance",
     "content": "Priority Sector Lending Certificates (PSLC) (REG-PSLC-001): Purpose: Enable banks with surplus PSL to sell certificates to banks with shortfall. Types: PSLC-Agriculture, PSLC-SF/MF (Small/Marginal Farmers), PSLC-Micro Enterprises, PSLC-General. Trading Platform: RBI's e-Kuber portal. Validity: Financial year in which it is issued. Premium: Market-determined premium paid by buying bank to selling bank. Settlement: Net settlement on trade date. Benefits: Shortfall banks can meet targets without actual lending. Surplus banks earn premium income. Promotes PSL lending in banking system."},

    {"id": "GEN-003", "title": "DICGC Insurance Coverage", "category": "operations", "access_level": "general",
     "content": "DICGC (Deposit Insurance and Credit Guarantee Corporation) Coverage (REF-GEN-003): Coverage Amount: Up to INR 5,00,000 per depositor per bank (enhanced from INR 1,00,000 in February 2020). Covers: All deposits (savings, current, FD, RD) in insured banks. Same depositor in different branches of same bank - aggregate up to INR 5 lakhs. Same depositor in different banks - each bank covered separately. Joint Accounts: Treated as separate from individual accounts. Premium: Paid by the bank (not customer). Not Covered: Deposits of foreign governments, deposits of central/state governments. Payout Timeline: Within 90 days of bank being placed under All-Inclusive Directions."},

    {"id": "GEN-004", "title": "TDS on Banking Transactions", "category": "operations", "access_level": "general",
     "content": "TDS (Tax Deducted at Source) on Banking Transactions (REF-GEN-004): Interest on FD/RD: TDS @10% if interest exceeds INR 40,000/year (INR 50,000 for senior citizens). If PAN not provided, TDS @20%. Exemption: Submit Form 15G (below 60 years) or Form 15H (60 years and above) if total income below taxable limit. Cash Withdrawal: TDS @2% on cash withdrawals exceeding INR 1 crore in a financial year. TDS @5% if ITR not filed for preceding 3 years. Section 194N provisions. NRI Deposits: Interest on NRO accounts subject to TDS @30% (plus surcharge and cess). NRE accounts - interest fully exempt from tax ('exempt-exempt-exempt' status). Lower/NIL TDS: Apply for certificate under Section 197 for lower deduction. DTAA benefits available for NRIs."},

    {"id": "GEN-005", "title": "NRI Banking Services", "category": "operations", "access_level": "general",
     "content": "NRI Banking Services (SOP-GEN-005): Account Types: NRE (Non-Resident External): Foreign earnings deposited. Interest tax-free. Fully repatriable. Maintained in INR. NRO (Non-Resident Ordinary): Indian income deposited. Interest taxable. Repatriation up to USD 1 million/year with CA certificate. FCNR(B): Foreign Currency Non-Resident (Banks). Maintained in foreign currency (USD, GBP, EUR, etc.). No currency risk. Tax-free interest. Minimum tenure 1 year, maximum 5 years. RFC (Resident Foreign Currency): For returning NRIs. Can maintain foreign currency savings. KYC: OCI/PIO card, Passport, Overseas address proof. Loans: NRIs can avail home loans in India (up to 80% LTV). Cannot get agricultural land loans."},

    {"id": "GEN-006", "title": "Grievance Redressal Mechanism", "category": "customer_service", "access_level": "general",
     "content": "Grievance Redressal Mechanism (POL-GEN-006): Internal Mechanism: Every branch has designated Grievance Redressal Officer. Complaints acknowledged within 2 working days. Resolution within 7-30 days based on complexity. Escalation: Level 1 - Branch Level (Branch Manager). Level 2 - Zonal/Regional Level (Zonal Manager). Level 3 - Head Office (Nodal Officer). Level 4 - Board Level (Customer Service Committee of Board). External Mechanism: RBI Ombudsman - free, no lawyer needed. Consumer Forum - CDRC for compensation claims. Legal: Civil courts as last resort. Customer Service Committee: Board-level committee reviews complaints quarterly. Systemic improvements based on complaint trends. Annual report on customer service initiatives published."},

    {"id": "GEN-007", "title": "Green and Sustainable Banking", "category": "operations", "access_level": "general",
     "content": "Green and Sustainable Banking Initiatives (POL-GEN-007): Digital-First Approach: Encouraging digital transactions to reduce paper usage. E-statements replacing physical statements. Green Lending: Preferential rates for green energy projects. Solar, wind, and EV financing schemes. ESG Framework: Environmental, Social, and Governance factors integrated into credit assessment. Carbon footprint reporting. RBI Guidelines: Framework for acceptance of Green Deposits (2023). Green deposit proceeds used only for listed green activities: Renewable energy, Energy efficiency, Clean transportation, Climate change adaptation, Sustainable water management. Third-party verification of green deposit utilization required."},

    {"id": "GEN-008", "title": "Cyber Security Framework for Banks", "category": "risk", "access_level": "compliance",
     "content": "Cyber Security Framework for Banks (POL-CYBER-001): As per RBI Circular on Cyber Security Framework (June 2016): Governance: Board-approved cyber security policy. CISO (Chief Information Security Officer) appointment mandatory. SOC (Security Operations Center): 24x7 monitoring. Real-time threat detection and incident response. Incident Response: Cyber incidents reported to CERT-In within 6 hours. RBI to be notified for significant incidents. Pen Testing: Annual vulnerability assessment and penetration testing (VAPT). Red Team exercises for critical systems. Phishing Simulation: Quarterly employee awareness exercises. Capacity: Dedicated budget for cyber security (minimum specified by regulation). Security Audits: IS Audit at least annually. SWIFT CSP (Customer Security Programme) compliance mandatory."},

    {"id": "GEN-009", "title": "Financial Literacy and Inclusion", "category": "operations", "access_level": "general",
     "content": "Financial Literacy and Inclusion Initiatives (REF-GEN-009): Financial Literacy Centers (FLC): Banks maintain FLCs for spreading financial awareness. Conduct Outdoor Financial Literacy Camps in villages and wards. Topics: Savings habits, Insurance awareness, Pension planning, Digital payments, Fraud prevention. Business Correspondents (BC): Agents of bank providing banking services in unbanked areas. Services: Account opening, Cash deposit/withdrawal, Remittances, Balance enquiry. Banking Outlets: Every village with population 5,000+ must have banking outlet. Ultra Small Branches, BC outlets, ATMs, Mobile banking vans. PMJDY: Financial inclusion flagship scheme - every household must have bank account. Over 50 crore accounts opened under PMJDY."},

    {"id": "GEN-010", "title": "Succession and Legal Heir Claims", "category": "operations", "access_level": "general",
     "content": "Succession and Legal Heir Claims (SOP-GEN-010): With Nomination: Nominee can claim deposits by submitting: Death certificate, KYC of nominee, Indemnity bond, Letter of claim. TAT: 15 working days. Without Nomination: For amounts up to INR 1,00,000: Indemnity bond, Letter from all legal heirs, No objection from other heirs. For amounts above INR 1,00,000: Succession Certificate from court OR Probate of Will OR Letter of Administration. Documents: Death certificate (original), Relationship proof, KYC of claimant, Legal heir certificate from revenue authorities. Disputed Claims: Bank may insist on court order if dispute among heirs. Interest continues on deposits after death until claim settlement."},
]


def get_all_documents():
    """Return all banking knowledge base documents."""
    return BANKING_KNOWLEDGE_BASE


def get_documents_by_category(category):
    """Return documents filtered by category."""
    return [doc for doc in BANKING_KNOWLEDGE_BASE if doc["category"] == category]


def get_document_by_id(doc_id):
    """Return a single document by ID."""
    for doc in BANKING_KNOWLEDGE_BASE:
        if doc["id"] == doc_id:
            return doc
    return None


def get_categories():
    """Return all unique categories."""
    return list(set(doc["category"] for doc in BANKING_KNOWLEDGE_BASE))


def get_kb_stats():
    """Return knowledge base statistics."""
    docs = BANKING_KNOWLEDGE_BASE
    categories = {}
    for doc in docs:
        cat = doc["category"]
        categories[cat] = categories.get(cat, 0) + 1
    
    return {
        "total_documents": len(docs),
        "categories": categories,
        "category_count": len(categories),
    }
